version: '3.3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_HOST=db
        restart: always

    back:
        build:
            context: .
            dockerfile: DockerfileBack
        command: ["/code/django-entrypoint.sh"]
        environment:
            - SECRET_KEY='2*0@lqe83p-8n()egy4)t%04nobpfq#eye!m=l9jh#_u2ix*ai'
        ports:
            - 8000:8000
        depends_on:
            - db

    front:
        build:
            context: .
            dockerfile: DockerfileFront
        ports:
            - 8080:8080
        environment:
            - STATIC_URL=back
        depends_on:
            - back
